// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnOYBTVxIK_x6zKDrqFsEDGePYMyvZ65k',
    appId: '1:802917998810:web:f728e2e632eb8b43ffc5e3',
    messagingSenderId: '802917998810',
    projectId: 'noble-feat-404013',
    authDomain: 'noble-feat-404013.firebaseapp.com',
    storageBucket: 'noble-feat-404013.appspot.com',
    measurementId: 'G-FSPC1PMLL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWPOah4ecgFiTF5rFacvtQMiymdFHFJpk',
    appId: '1:802917998810:android:a6acf96b509622c2ffc5e3',
    messagingSenderId: '802917998810',
    projectId: 'noble-feat-404013',
    storageBucket: 'noble-feat-404013.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKOV8miI7uFxFLjcQNR6WsMX65dG5wEm8',
    appId: '1:802917998810:ios:016c8dde31b045faffc5e3',
    messagingSenderId: '802917998810',
    projectId: 'noble-feat-404013',
    storageBucket: 'noble-feat-404013.appspot.com',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKOV8miI7uFxFLjcQNR6WsMX65dG5wEm8',
    appId: '1:802917998810:ios:e7e71dfba1826490ffc5e3',
    messagingSenderId: '802917998810',
    projectId: 'noble-feat-404013',
    storageBucket: 'noble-feat-404013.appspot.com',
    iosBundleId: 'com.example.testDrive.RunnerTests',
  );
}
